apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: liferay
  namespace: YOUR_NAMESPACE
spec:
  serviceName: "liferay"
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      app: liferay
  template:
    metadata:
      labels:
        app: liferay
    spec:
      containers:
      - name: liferay
        image: YOUR_IMAGE
        ports:
        - containerPort: 8443
          name: liferay
        env:
        - name: LIFERAY_JVM_OPTS
          value: "-Xms6g -Xmx6g -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"
        - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_DRIVER_UPPERCASEC_lass_UPPERCASEN_ame
          value: "YOUR_JDBC_DRIVER"
        - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
          valueFrom:
            secretKeyRef:
              name: liferay-db-credentials
              key: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_URL
        - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
          valueFrom:
            secretKeyRef:
              name: liferay-db-credentials
              key: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_USERNAME
        - name: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
          valueFrom:
            secretKeyRef:
              name: liferay-db-credentials
              key: LIFERAY_JDBC_PERIOD_DEFAULT_PERIOD_PASSWORD
        - name: LIFERAY_UPGRADE_PERIOD_DATABASE_PERIOD_AUTO_PERIOD_RUN
          value: "true"
        resources:
          requests:
            memory: "5Gi"
            cpu: "5"
          limits:
            memory: "8Gi"
            cpu: "5"
---
apiVersion: v1
kind: Service
metadata:
  name: liferay
  namespace: YOUR_NAMESPACE
  labels:
    service: liferay
spec:
  type: NodePort
  ports:
  - port: 8443
    protocol: TCP
    targetPort: 8443
    name: liferay
  selector:
    app: liferay
---
apiVersion: v1
kind: Service
metadata:
  name: liferay-cluster
  namespace: YOUR_NAMESPACE
  labels:
    name: liferay-cluster
spec:
  clusterIP: None
  selector:
    app: liferay
  ports:
  - port: 7800
    name: jgroupsliferay-control
    protocol: TCP
    targetPort: 7800
  - port: 7801
    name: jgroupsliferay-transport
    protocol: TCP
    targetPort: 7801
